### ISSUE TITLE
100% cpu

### ISSUE THREAD

**Issue by cxxxr** [fukamachi/jsonrpc#8]
ChanLを使うようになったhttps://github.com/fukamachi/jsonrpc/commit/bba6c569acd427dce1ba7711afcf9c987e7eceb6 からCPU使用率が常に100％になりました
ChanLの方に問題があるのかもしれませんが一応ここに報告しておきます

**Comment by fukamachi** [comment]
報告ありがとうございます。
`chanl:select` がconditionによるブロックをせずナイーブな実装になっているのが原因のような気がします。
直します。

Thank you for reporting.
Perhaps, it's because `chanl:select` is a simple implementation doesn't block.
I'm gonna fix it.

**Comment by cxxxr** [comment]
確認しました、ありがとうございます。
Thank you for fixing.
It worked well.
